#!/usr/bin/env python3
"""Write ZoltParity/jolt_sources.zig: the Jolt C++ sources that `zig build parity` compiles.

The parity harness builds the C++ library with Zig's C++ compiler as the reference implementation.
GPU compute backends (DX12/Vulkan/Metal) are excluded. Re-run after syncing Jolt with upstream.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EXCLUDE = ("Compute/DX12/", "Compute/VK/", "Compute/MTL/")

files = []
for dirpath, _, filenames in os.walk(os.path.join(ROOT, "Jolt")):
    for name in filenames:
        if name.endswith(".cpp"):
            path = os.path.relpath(os.path.join(dirpath, name), os.path.join(ROOT, "Jolt")).replace(os.sep, "/")
            if not path.startswith(EXCLUDE):
                files.append(path)
files.sort(key=str.lower)

out = ["//! Generated by tools/gen_jolt_sources.py, do not edit.",
       "//! Jolt C++ sources (relative to Jolt/) compiled by `zig build parity` as the reference implementation.",
       "",
       "pub const files = [_][]const u8{"]
out += [f'    "{f}",' for f in files]
out += ["};", ""]
with open(os.path.join(ROOT, "ZoltParity", "jolt_sources.zig"), "w", encoding="utf-8") as f:
    f.write("\n".join(out))
print(f"Wrote ZoltParity/jolt_sources.zig ({len(files)} files)")
