//! Port of: Jolt/Core/Color.h, Jolt/Core/Color.cpp
//! Status: complete

const std = @import("std");
const Vec4 = @import("../Math/Vec4.zig").Vec4;

/// Class that holds an RGBA color with 8-bits per component
pub const Color = extern struct {
    /// Red channel
    r: u8,
    /// Green channel
    g: u8,
    /// Blue channel
    b: u8,
    /// Alpha channel
    a: u8,

    /// Construct from the combined value for red, green, blue and alpha (explicit Color(uint32))
    pub fn fromUInt32(color: u32) Color {
        return @bitCast(color);
    }

    /// Construct from components, use 255 for an opaque color (the C++ default for alpha)
    pub fn init(r: u8, g: u8, b: u8, a: u8) Color {
        return .{ .r = r, .g = g, .b = b, .a = a };
    }

    /// Construct opaque color from components (Color(r, g, b))
    pub fn initRgb(r: u8, g: u8, b: u8) Color {
        return init(r, g, b, 255);
    }

    /// Copy a color with a different alpha (Color(ColorArg, uint8))
    pub fn withAlpha(self: Color, alpha: u8) Color {
        return init(self.r, self.g, self.b, alpha);
    }

    /// Comparison (operator ==)
    pub fn eql(self: Color, other: Color) bool {
        return self.getUInt32() == other.getUInt32();
    }

    /// Convert to uint32
    pub fn getUInt32(self: Color) u32 {
        return @bitCast(self);
    }

    /// Element access, 0 = red, 1 = green, 2 = blue, 3 = alpha (operator () const)
    pub fn getComponent(self: Color, idx: u32) u8 {
        std.debug.assert(idx < 4);
        const components: [4]u8 = @bitCast(self);
        return components[idx];
    }

    /// Element access, 0 = red, 1 = green, 2 = blue, 3 = alpha (operator ())
    pub fn setComponent(self: *Color, idx: u32, value: u8) void {
        std.debug.assert(idx < 4);
        var components: [4]u8 = @bitCast(self.*);
        components[idx] = value;
        self.* = @bitCast(components);
    }

    /// Multiply two colors (operator * (const Color &))
    pub fn mul(self: Color, other: Color) Color {
        return init(
            @intCast((@as(u32, self.r) * other.r) >> 8),
            @intCast((@as(u32, self.g) * other.g) >> 8),
            @intCast((@as(u32, self.b) * other.b) >> 8),
            @intCast((@as(u32, self.a) * other.a) >> 8),
        );
    }

    /// Multiply color with intensity in the range [0, 1] (operator * (float))
    pub fn mulScalar(self: Color, intensity: f32) Color {
        return init(
            @intFromFloat(@as(f32, @floatFromInt(self.r)) * intensity),
            @intFromFloat(@as(f32, @floatFromInt(self.g)) * intensity),
            @intFromFloat(@as(f32, @floatFromInt(self.b)) * intensity),
            self.a,
        );
    }

    /// Convert to Vec4 with range [0, 1]
    pub fn toVec4(self: Color) Vec4 {
        return Vec4.init(@floatFromInt(self.r), @floatFromInt(self.g), @floatFromInt(self.b), @floatFromInt(self.a)).divScalar(255.0);
    }

    /// Get grayscale intensity of color
    pub fn getIntensity(self: Color) u8 {
        return @intCast((@as(u32, self.r) * 54 + @as(u32, self.g) * 183 + @as(u32, self.b) * 19) >> 8);
    }

    /// Get a visually distinct color
    pub fn getDistinctColor(index: i32) Color {
        std.debug.assert(index >= 0);
        return distinct_colors[@intCast(@mod(index, @as(i32, distinct_colors.len)))];
    }

    /// Get a color value on the gradient from green through yellow to red
    /// value: Value in the range [0, 1], 0 = green, 0.5 = yellow, 1 = red
    pub fn greenRedGradient(value: f32) Color {
        if (value < 0.0)
            return green
        else if (value < 0.5)
            return initRgb(@intFromFloat(510.0 * value), 255, 0)
        else if (value < 1.0)
            return initRgb(255, @intFromFloat(510.0 * (1.0 - value)), 0)
        else
            return red;
    }

    // Predefined colors
    pub const black = initRgb(0, 0, 0);
    pub const dark_red = initRgb(128, 0, 0);
    pub const red = initRgb(255, 0, 0);
    pub const dark_green = initRgb(0, 128, 0);
    pub const green = initRgb(0, 255, 0);
    pub const dark_blue = initRgb(0, 0, 128);
    pub const blue = initRgb(0, 0, 255);
    pub const yellow = initRgb(255, 255, 0);
    pub const purple = initRgb(255, 0, 255);
    pub const cyan = initRgb(0, 255, 255);
    pub const orange = initRgb(255, 128, 0);
    pub const dark_orange = initRgb(128, 64, 0);
    pub const grey = initRgb(128, 128, 128);
    pub const light_grey = initRgb(192, 192, 192);
    pub const white = initRgb(255, 255, 255);

    // Generated by: http://phrogz.net/css/distinct-colors.html (this algo: https://en.wikipedia.org/wiki/Color_difference#CMC_l:c_.281984.29)
    const distinct_colors = [_]Color{ initRgb(255, 0, 0), initRgb(204, 143, 102), initRgb(226, 242, 0), initRgb(41, 166, 124), initRgb(0, 170, 255), initRgb(69, 38, 153), initRgb(153, 38, 130), initRgb(229, 57, 80), initRgb(204, 0, 0), initRgb(255, 170, 0), initRgb(85, 128, 0), initRgb(64, 255, 217), initRgb(0, 75, 140), initRgb(161, 115, 230), initRgb(242, 61, 157), initRgb(178, 101, 89), initRgb(140, 94, 0), initRgb(181, 217, 108), initRgb(64, 242, 255), initRgb(77, 117, 153), initRgb(157, 61, 242), initRgb(140, 0, 56), initRgb(127, 57, 32), initRgb(204, 173, 51), initRgb(64, 255, 64), initRgb(38, 145, 153), initRgb(0, 102, 255), initRgb(242, 0, 226), initRgb(153, 77, 107), initRgb(229, 92, 0), initRgb(140, 126, 70), initRgb(0, 179, 71), initRgb(0, 194, 242), initRgb(27, 0, 204), initRgb(230, 115, 222), initRgb(127, 0, 17) };

    comptime {
        std.debug.assert(@sizeOf(Color) == 4);
    }
};

test "Color" {
    const c = Color.init(10, 20, 30, 40);
    try std.testing.expect(Color.fromUInt32(c.getUInt32()).eql(c));
    try std.testing.expectEqual(@as(u8, 30), c.getComponent(2));
    var d = c;
    d.setComponent(3, 255);
    try std.testing.expect(d.eql(c.withAlpha(255)));
    try std.testing.expect(Color.white.mul(c).eql(Color.init(9, 19, 29, 39)));
    try std.testing.expect(Color.white.mulScalar(0.5).eql(Color.init(127, 127, 127, 255)));
    try std.testing.expect(Color.white.toVec4().eql(Vec4.one()));
    try std.testing.expectEqual(@as(u8, 255), Color.white.getIntensity());
    try std.testing.expect(Color.getDistinctColor(36).eql(Color.getDistinctColor(0)));
    try std.testing.expect(Color.greenRedGradient(-1).eql(Color.green));
    try std.testing.expect(Color.greenRedGradient(0.25).eql(Color.initRgb(127, 255, 0)));
    try std.testing.expect(Color.greenRedGradient(0.75).eql(Color.initRgb(255, 127, 0)));
    try std.testing.expect(Color.greenRedGradient(2).eql(Color.red));
}
